version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"  # Expose PostgreSQL on your host machine
